name: preview

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: ['*', '!main']
  pull_request:
    branches: ['*', '!main']
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build
      - name: Build
        run: nix develop --command bash -c "npm i && npm run build"
      # Deploy Preview to Cloudflare Workers
      # Ref: https://zenn.dev/lalalatotoro/articles/b8fa632b53d332
      # Ref: https://zenn.dev/nikomaru/articles/0cea1b1e2fd4f2
      # Ref: https://developers.cloudflare.com/workers/wrangler/commands/#versions-upload
      - name: Deploy Preview to Cloudflare Workers
        id: preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            versions upload --message "Deployed a Preview by GitHub Actions: branch ${{ github.ref_name }}"
      # Ref: https://github.com/actions/github-script
      # Ref: https://zenn.dev/yamachu/articles/0b4e520229239d
      - name: Comment Preview Summary
        env:
          COMMIT_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number || '' }}
          COMMAND_OUTPUT: ${{ steps.preview.outputs.command-output }}
          DEPLOYMENT_URL: ${{ steps.preview.outputs.deployment-url }}
          PAGES_ENV: "${{ steps.preview.outputs.pages-environment }}"
        uses: actions/github-script@v8
        with:
          script: | #```typescript
            const commitSha = process.env.COMMIT_SHA;
            const prNumber = process.env.PR_NUMBER;
            const commandOutput = process.env.COMMAND_OUTPUT;
            const deploymentUrl = process.env.DEPLOYMENT_URL;
            const deploymentEnv = process.env.PAGES_ENV;
            if (!deploymentUrl) {
              console.error("No deployment URL available.");
              return;
            }
            if (prNumber === '') {
              console.info("Not a pull request, skipping comment.");
              return;
            }
            const commentBody = `
              # Deploying ${deploymentEnv} with 🚀 Cloudflare Workers
              ---
              <table>
                <tbody>
                  <tr>
                    <td>Latest commit:</td>
                    <td>${commitSha}</td>
                  </tr>
                  <tr>
                    <td>Preview URL:</td>
                    <td>${deploymentUrl}</td>
                  </tr>
                </tbody>
              </table>

              <details>
                <summary>View logs</summary>
                ${commandOutput}
              </details>
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(prNumber, 10),
              body: commentBody,
            });
          #```
