name: test

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: ESLint Verification
        run: nix develop --command bash -c "npm i && npm run lint"
      - name: Test Verification
        run: nix develop --command bash -c "npm i && npm run test"
      - name: Build Verification
        run: nix develop --command bash -c "npm i && npm run build"
